#!/usr/bin/env python3
"""
NVFlare Provisioner Service
Uses the NVFlare provisioner directly like in blob.py
"""

import os
import tempfile
import subprocess
import json
import zipfile
import io
import shutil
from pathlib import Path
from .models import Project, Server, Client, Admin

# Import NVFlare provisioner components
try:
    from nvflare.lighter.constants import PropKey
    from nvflare.lighter.entity import Project as ProvProject
    from nvflare.lighter.impl.aws import AWSBuilder
    from nvflare.lighter.impl.azure import AzureBuilder
    from nvflare.lighter.impl.cert import CertBuilder
    from nvflare.lighter.impl.signature import SignatureBuilder
    from nvflare.lighter.impl.static_file import StaticFileBuilder
    from nvflare.lighter.impl.workspace import WorkspaceBuilder
    from nvflare.lighter.provisioner import Provisioner
    NVFLARE_AVAILABLE = True
except ImportError:
    print("Warning: NVFlare not available, falling back to CLI approach")
    NVFLARE_AVAILABLE = False

class DummyLogger:
    """This dummy logger is used to suppress all log messages generated by the Provisioner, except for errors.
    We print error messages to stdout.
    """

    def info(self, msg: str):
        pass

    def error(self, msg: str):
        print(f"ERROR: {msg}")

    def debug(self, msg: str):
        pass

    def warning(self, msg: str):
        pass

class NVFlareProvisionerService:
    """Service for generating NVFlare project configurations using the provisioner directly"""
    
    def __init__(self, workspace_dir="workspace"):
        self.workspace_dir = workspace_dir
        os.makedirs(workspace_dir, exist_ok=True)
    
    def _get_provisioner(self, root_dir: str, scheme, docker_image=None):
        """Get the NVFlare provisioner with all necessary builders"""
        overseer_agent = {
            "path": "nvflare.ha.dummy_overseer_agent.DummyOverseerAgent",
            "overseer_exists": False,
            "args": {"sp_end_point": "server:8002:8003"},
        }
        
        builders = [
            WorkspaceBuilder(),
            StaticFileBuilder(
                config_folder="config",
                scheme=scheme,
                docker_image=docker_image,
                overseer_agent=overseer_agent,
            ),
            AWSBuilder(),
            AzureBuilder(),
            CertBuilder(),
            SignatureBuilder(),
        ]

        # TBD: need to add Packager object to the provisioner!
        packager = None
        return Provisioner(root_dir, builders, packager)
    
    def provision_project(self, project_id, force_reprovision=False):
        """Provision a project using the NVFlare provisioner"""
        if not NVFLARE_AVAILABLE:
            print("NVFlare not available, falling back to CLI approach")
            return self._provision_via_cli(project_id, force_reprovision)
        
        try:
            # Get project data
            project = Project.query.get(project_id)
            if not project:
                raise ValueError(f"Project {project_id} not found")
            
            servers = Server.query.filter_by(project_id=project_id).all()
            clients = Client.query.filter_by(project_id=project_id).all()
            admins = Admin.query.filter_by(project_id=project_id).all()
            
            print(f"Provisioning project: {project.name}")
            print(f"Servers: {len(servers)}, Clients: {len(clients)}, Admins: {len(admins)}")
            
            # Check if already provisioned
            if not force_reprovision:
                existing_workspace = self._get_existing_workspace(project_id)
                if existing_workspace:
                    print(f"Project {project_id} already provisioned, using existing workspace: {existing_workspace}")
                    return existing_workspace
            
            # Create temporary directory for provisioning
            with tempfile.TemporaryDirectory() as tmp_dir:
                print(f"Using temporary directory: {tmp_dir}")
                
                # Get provisioner
                scheme = getattr(project, 'scheme', 'grpc')
                docker_image = getattr(project, 'app_location', 'nvflare/nvflare')
                if docker_image and ' ' in docker_image:
                    docker_image = docker_image.split(" ")[-1]
                
                provisioner = self._get_provisioner(tmp_dir, scheme, docker_image)
                
                # Create project properties
                proj_props = {PropKey.API_VERSION: getattr(project, 'api_version', 3)}
                if hasattr(project, 'project_props') and project.project_props:
                    try:
                        proj_props.update(json.loads(project.project_props))
                    except:
                        pass
                
                # Create the provisioner project
                prov_project = ProvProject(
                    getattr(project, 'short_name', project.name),
                    getattr(project, 'description', ''),
                    props=proj_props,
                    root_private_key=None,  # We'll generate this
                    serialized_root_cert=None,  # We'll generate this
                )
                
                # Add servers
                for server in servers:
                    server_props = {
                        PropKey.FED_LEARN_PORT: server.fed_learn_port,
                        PropKey.ADMIN_PORT: server.admin_port,
                        PropKey.DEFAULT_HOST: server.name,
                        PropKey.CONN_SECURITY: getattr(server, 'connection_security', 'mtls'),
                    }
                    
                    if hasattr(server, 'props') and server.props:
                        try:
                            server_props.update(json.loads(server.props))
                        except:
                            pass
                    
                    prov_project.set_server(
                        name=server.name,
                        org=server.org,
                        props=server_props,
                    )
                
                # Add clients
                for client in clients:
                    client_props = {}
                    
                    if hasattr(client, 'capacity') and client.capacity:
                        try:
                            client_props[PropKey.CAPACITY] = json.loads(client.capacity)
                        except:
                            pass
                    
                    if hasattr(client, 'props') and client.props:
                        try:
                            client_props.update(json.loads(client.props))
                        except:
                            pass
                    
                    prov_project.add_client(
                        name=client.name,
                        org=client.org,
                        props=client_props
                    )
                
                # Add admins
                for admin in admins:
                    admin_props = {PropKey.ROLE: getattr(admin, 'role', 'project_admin')}
                    
                    if hasattr(admin, 'props') and admin.props:
                        try:
                            admin_props.update(json.loads(admin.props))
                        except:
                            pass
                    
                    prov_project.add_admin(
                        name=admin.email,
                        org=admin.org,
                        props=admin_props
                    )
                
                # Provision the project
                print("Calling provisioner.provision()...")
                ctx = provisioner.provision(prov_project, logger=DummyLogger())
                result_dir = ctx.get_result_location()
                
                print(f"Provisioning completed. Result directory: {result_dir}")
                print(f"Result contents: {os.listdir(result_dir)}")
                
                # Copy to final workspace location
                final_workspace = os.path.join(self.workspace_dir, f"project_{project_id}")
                if os.path.exists(final_workspace):
                    shutil.rmtree(final_workspace)
                
                shutil.copytree(result_dir, final_workspace)
                print(f"Copied to final workspace: {final_workspace}")
                
                return final_workspace
                
        except Exception as e:
            print(f"Error provisioning project: {e}")
            raise
    
    def _provision_via_cli(self, project_id, force_reprovision=False):
        """Fallback to CLI provisioning if NVFlare is not available"""
        print("Using CLI fallback provisioning...")
        # This would call the existing CLI-based provisioning
        # For now, just return None to indicate fallback needed
        return None
    
    def _get_existing_workspace(self, project_id):
        """Get existing workspace if project is already provisioned"""
        workspace = os.path.join(self.workspace_dir, f"project_{project_id}")
        if not os.path.exists(workspace):
            return None
        
        # Look for the prod_00 directory
        for item in os.listdir(workspace):
            project_dir = os.path.join(workspace, item)
            if os.path.isdir(project_dir):
                prod_dir = os.path.join(project_dir, 'prod_00')
                if os.path.exists(prod_dir):
                    return prod_dir
        
        return None
    
    def generate_startup_kit(self, project_id, item_type, item_id=None):
        """Generate startup kit for a specific item or the entire project"""
        workspace = self._get_existing_workspace(project_id)
        if not workspace:
            raise ValueError(f"Project {project_id} not provisioned")
        
        if item_type == 'all':
            return self._generate_all_startup_kits(workspace)
        else:
            return self._generate_item_startup_kit(workspace, item_type, item_id)
    
    def _generate_item_startup_kit(self, workspace, item_type, item_id):
        """Generate startup kit for a specific item"""
        # Find the appropriate directory based on item type
        target_dir = None
        
        for item in os.listdir(workspace):
            item_path = os.path.join(workspace, item)
            if os.path.isdir(item_path):
                if item_type == 'server' and (item.endswith('.com') or item.endswith('.org')):
                    target_dir = item_path
                    break
                elif item_type == 'client' and item.startswith('site-'):
                    target_dir = item_path
                    break
                elif item_type == 'admin' and '@' in item:
                    target_dir = item_path
                    break
        
        if not target_dir:
            raise ValueError(f"Could not find {item_type} directory in workspace")
        
        # Create zip file
        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            for root, dirs, files in os.walk(target_dir):
                for file in files:
                    file_path = os.path.join(root, file)
                    arc_name = os.path.relpath(file_path, target_dir)
                    zip_file.write(file_path, arc_name)
        
        zip_buffer.seek(0)
        return zip_buffer, f"{os.path.basename(target_dir)}.zip"
    
    def _generate_all_startup_kits(self, workspace):
        """Generate startup kits for all items"""
        all_kits = {}
        
        for item in os.listdir(workspace):
            item_path = os.path.join(workspace, item)
            if os.path.isdir(item_path):
                if item.endswith('.com') or item.endswith('.org'):
                    # Server
                    kit_buffer, kit_name = self._generate_item_startup_kit(workspace, 'server', None)
                    all_kits['server'] = (kit_buffer, kit_name)
                elif item.startswith('site-'):
                    # Client
                    kit_buffer, kit_name = self._generate_item_startup_kit(workspace, 'client', None)
                    all_kits['client'] = (kit_buffer, kit_name)
                elif '@' in item:
                    # Admin
                    kit_buffer, kit_name = self._generate_item_startup_kit(workspace, 'admin', None)
                    all_kits['admin'] = (kit_buffer, kit_name)
        
        return all_kits
