#!/usr/bin/env python3
"""
NVFlare Provisioner Service
Uses the NVFlare provisioner directly like in blob.py
"""

import os
import tempfile
import subprocess
import json
import zipfile
import io
import shutil
from pathlib import Path
from .models import Project, Server, Client, Admin

# Import NVFlare provisioner components
try:
    from nvflare.lighter.constants import (
        PropKey, TemplateSectionKey, ProvFileName, ConnSecurity, 
        CtxKey, ProvisionMode
    )
    from nvflare.lighter.entity import Project as ProvProject, Participant, ParticipantType
    from nvflare.lighter.impl.aws import AWSBuilder
    from nvflare.lighter.impl.azure import AzureBuilder
    from nvflare.lighter.impl.cert import CertBuilder
    from nvflare.lighter.impl.signature import SignatureBuilder
    from nvflare.lighter.impl.static_file import StaticFileBuilder
    from nvflare.lighter.impl.workspace import WorkspaceBuilder
    from nvflare.lighter.provisioner import Provisioner
    NVFLARE_AVAILABLE = True
except ImportError:
    print("Warning: NVFlare not available, falling back to CLI approach")
    NVFLARE_AVAILABLE = False

class DummyLogger:
    """This dummy logger is used to suppress all log messages generated by the Provisioner, except for errors.
    We print error messages to stdout.
    """

    def info(self, msg: str):
        pass

    def error(self, msg: str):
        print(f"ERROR: {msg}")

    def debug(self, msg: str):
        pass

    def warning(self, msg: str):
        pass

class CustomStaticFileBuilder(StaticFileBuilder):
    """Custom StaticFileBuilder that configures server to listen on both ports"""
    
    def _build_server(self, server, ctx):
        """Override _build_server to configure multiple port listening"""
        project = ctx.get_project()
        dest_dir = ctx.get_kit_dir(server)

        admin_port = ctx.get(CtxKey.ADMIN_PORT)
        fed_learn_port = ctx.get(CtxKey.FED_LEARN_PORT)
        
        # Use single port target for service discovery (standard NVFlare behavior)
        target = f"{server.name}:{fed_learn_port}"  # Only fed_learn_port for service discovery
        sp_end_point = f"{server.name}:{fed_learn_port}:{admin_port}"
        conn_sec = self._build_conn_properties(server, ctx)

        print(f"🔧 CustomStaticFileBuilder: Setting server target to {target}")
        print(f"🔧 CustomStaticFileBuilder: Server will listen on port {fed_learn_port}")

        # Build the fed_server.json with correct structure including admin_host and admin_port
        self._build_fed_server_json(dest_dir, project, server, target, conn_sec, sp_end_point, admin_port)

        # Configure server to listen on fed_learn_port
        self._configure_server_listeners(server, ctx, fed_learn_port, admin_port)

        # Call the rest of the original _build_server method
        self._build_comm_config_for_internal_listener(server)

        replacement_dict = {
            "admin_port": admin_port,
            "fed_learn_port": fed_learn_port,
            "config_folder": self.config_folder,
            "docker_image": self.docker_image,
            "org_name": server.org,
            "type": "server",
            "app_name": "server_train",
            "cln_uid": "",
        }

        if self.docker_image:
            ctx.build_from_template(
                dest_dir,
                TemplateSectionKey.DOCKER_SERVER_SH,
                ProvFileName.DOCKER_SH,
                replacement=replacement_dict,
                exe=True,
            )

        ctx.build_from_template(
            dest_dir,
            TemplateSectionKey.START_SERVER_SH,
            ProvFileName.START_SH,
            replacement={"ha_mode": "false"},
            exe=True,
        )

        ctx.build_from_template(
            dest_dir,
            TemplateSectionKey.SUB_START_SH,
            ProvFileName.SUB_START_SH,
            replacement=replacement_dict,
            exe=True,
        )

        ctx.build_from_template(dest_dir, TemplateSectionKey.STOP_FL_SH, ProvFileName.STOP_FL_SH, exe=True)

        # local folder creation
        dest_dir = ctx.get_local_dir(server)

        ctx.build_from_template(dest_dir, TemplateSectionKey.LOG_CONFIG, ProvFileName.LOG_CONFIG_DEFAULT, exe=False)

        ctx.build_from_template(
            dest_dir, TemplateSectionKey.LOCAL_SERVER_RESOURCES, ProvFileName.RESOURCES_JSON_DEFAULT, exe=False
        )

        ctx.build_from_template(
            dest_dir, TemplateSectionKey.SAMPLE_PRIVACY, ProvFileName.PRIVACY_JSON_SAMPLE, exe=False
        )

        # other builder (e.g. CC) can set the AUTHZ_SECTION_KEY to specify authorization policies for the server
        authz_section_key = server.get_prop(PropKey.AUTHZ_SECTION_KEY, TemplateSectionKey.DEFAULT_AUTHZ)

        ctx.build_from_template(dest_dir, authz_section_key, ProvFileName.AUTHORIZATION_JSON_DEFAULT, exe=False)

        # workspace folder file
        dest_dir = ctx.get_ws_dir(server)
        ctx.build_from_template(dest_dir, TemplateSectionKey.SERVER_README, ProvFileName.README_TXT, exe=False)
        


    def _configure_server_listeners(self, server, ctx, fed_learn_port: int, admin_port: int):
        """Configure server to listen on fed_learn_port"""
        print(f"🔧 Configuring server listener on port {fed_learn_port}")
        
        # Configure the listener for federated learning and admin operations
        listener_config = {
            PropKey.SCHEME: 'agrpc',
            PropKey.DEFAULT_HOST: server.get_default_host(),
            PropKey.PORT: fed_learn_port
        }
        
        # Set the listening_host for the server
        server.set_prop(PropKey.LISTENING_HOST, listener_config)
        
        print(f"🔧 Server listener configured:")
        print(f"  - Listener: {listener_config}")
    
    def _build_fed_server_json(self, dest_dir, project, server, target, conn_sec, sp_end_point, admin_port):
        """Build fed_server.json with correct structure including admin_host and admin_port"""
        import json
        import os
        
        # Create the correct fed_server.json structure
        fed_server_data = {
            "format_version": 2,
            "servers": [
                {
                    "name": project.name,
                    "service": {
                        "target": target,
                        "scheme": "agrpc"
                    },
                    "admin_host": server.name,  # Add admin_host
                    "admin_port": admin_port,   # Add admin_port
                    "ssl_private_key": "server.key",
                    "ssl_cert": "server.crt",
                    "ssl_root_cert": "rootCA.pem"
                }
            ],
            "overseer_agent": {
                "path": "nvflare.ha.dummy_overseer_agent.DummyOverseerAgent",
                "args": {
                    "sp_end_point": sp_end_point
                }
            }
        }
        
        # Connection security is handled by SSL certificates, no need to add connection_security property
        
        # Write the fed_server.json file
        fed_server_path = os.path.join(dest_dir, "..", "startup", ProvFileName.FED_SERVER_JSON)
        os.makedirs(os.path.dirname(fed_server_path), exist_ok=True)
        
        with open(fed_server_path, 'w') as f:
            json.dump(fed_server_data, f, indent=2)
        
        print(f"✅ Created fed_server.json with admin_host: {server.name}, admin_port: {admin_port}")
        print(f"✅ File written to: {fed_server_path}")
    
    def _build_fed_admin_json(self, dest_dir, sp_end_point):
        """Build fed_admin.json with exact structure matching working provision3 setup"""
        import json
        import os
        
        # Extract server name and admin port from sp_end_point
        parts = sp_end_point.split(':')
        server_name = parts[0]
        admin_port = int(parts[2]) if len(parts) > 2 else 8003
        
        # Create admin configuration with correct host and protocol
        fed_admin_data = {
            "format_version": 1,
            "admin": {
                "project_name": "project_2",
                "server_identity": server_name,  # Add server_identity to match certificate CN
                "with_file_transfer": True,
                "upload_dir": "transfer",
                "download_dir": "transfer",
                "with_login": True,
                "with_ssl": True,
                "cred_type": "cert",
                "client_key": "client.key",
                "client_cert": "client.crt",
                "ca_cert": "rootCA.pem",
                "prompt": "> ",
                "host": server_name,  # Use correct server hostname
                "port": admin_port,        # Connect to admin port
                "scheme": "agrpc",   # Use correct protocol
                "overseer_agent": {
                    "path": "nvflare.ha.dummy_overseer_agent.DummyOverseerAgent",
                    "args": {
                        "sp_end_point": sp_end_point
                    }
                }
            }
        }
        
        # Write the fed_admin.json file
        fed_admin_path = os.path.join(dest_dir, ProvFileName.FED_ADMIN_JSON)
        os.makedirs(os.path.dirname(fed_admin_path), exist_ok=True)
        
        with open(fed_admin_path, 'w') as f:
            json.dump(fed_admin_data, f, indent=2)
        
        print(f"✅ Created fed_admin.json with sp_end_point: {sp_end_point}")
        print(f"✅ File written to: {fed_admin_path}")

    def prepare_admin_config(self, admin, ctx):
        """Override prepare_admin_config to add overseer_agent configuration"""
        project = ctx.get_project()
        server = project.get_server()
        conn_sec = server.get_prop_fb(PropKey.CONN_SECURITY)
        if not conn_sec:
            conn_sec = 'mtls'

        uid_source = "user_input"
        provision_mode = ctx.get_provision_mode()
        if provision_mode == 'poc':
            uid_source = "cert"

        conn_host, conn_port = self._determine_conn_target(admin, ctx)
        if not conn_port:
            conn_port = ctx.get(CtxKey.ADMIN_PORT)
        
        # Force admin to connect to admin port (8003) instead of fed_learn_port (8002)
        admin_port = ctx.get(CtxKey.ADMIN_PORT)
        if admin_port:
            conn_port = admin_port

        # Get overseer agent configuration from project
        fed_learn_port = ctx.get(CtxKey.FED_LEARN_PORT)
        admin_port = ctx.get(CtxKey.ADMIN_PORT)
        if not fed_learn_port:
            fed_learn_port = 8002
        if not admin_port:
            admin_port = 8003
        # For admin, use the same sp_end_point as server: fed_learn_port:admin_port
        sp_end_point = f"{server.name}:{fed_learn_port}:{admin_port}"
        
        print(f"🔧 CustomStaticFileBuilder: Adding overseer_agent to admin config with sp_end_point: {sp_end_point}")

        # Use minimal admin configuration like the working provision3 setup
        replacement_dict = {
            "with_file_transfer": "true",
            "upload_dir": "transfer",
            "download_dir": "transfer",
            "with_login": "true",
            "with_ssl": "true",
            "cred_type": "cert",
            "prompt": "> ",
        }
        
        # Create custom fed_admin.json that matches the working provision3 setup exactly
        self._build_fed_admin_json(ctx.get_kit_dir(admin), sp_end_point)

        # create default resources in local
        ctx.build_from_template(
            dest_dir=ctx.get_local_dir(admin),
            temp_section=TemplateSectionKey.DEFAULT_ADMIN_RESOURCES,
            file_name=ProvFileName.RESOURCES_JSON_DEFAULT,
        )
    
    def _add_overseer_agent_to_admin_config(self, dest_dir, sp_end_point):
        """Add overseer_agent configuration to fed_admin.json"""
        import json
        import os
        
        fed_admin_path = os.path.join(dest_dir, ProvFileName.FED_ADMIN_JSON)
        if not os.path.exists(fed_admin_path):
            print(f"⚠️  fed_admin.json not found at {fed_admin_path}")
            return
        
        try:
            print(f"🔧 Reading fed_admin.json from: {fed_admin_path}")
            with open(fed_admin_path, 'r') as f:
                fed_admin_data = json.load(f)
            
            print(f"🔧 Current fed_admin.json content: {json.dumps(fed_admin_data, indent=2)}")
            
            # Add overseer_agent configuration
            if 'admin' not in fed_admin_data or not isinstance(fed_admin_data['admin'], dict):
                fed_admin_data['admin'] = {}
            fed_admin_data['admin']['overseer_agent'] = {
                "path": "nvflare.ha.dummy_overseer_agent.DummyOverseerAgent",
                "args": {
                    "sp_end_point": sp_end_point
                }
            }
            
            print(f"🔧 Updated fed_admin.json with sp_end_point: {sp_end_point}")
            
            # Write back the modified JSON
            with open(fed_admin_path, 'w') as f:
                json.dump(fed_admin_data, f, indent=2)
            print(f"✅ Added overseer_agent to {fed_admin_path} with sp_end_point: {sp_end_point}")
                
        except Exception as e:
            print(f"❌ Error adding overseer_agent to fed_admin.json: {e}")


class NVFlareProvisionerService:
    """Service for generating NVFlare project configurations using the provisioner directly"""
    
    def __init__(self, workspace_dir="workspace"):
        self.workspace_dir = workspace_dir
        os.makedirs(workspace_dir, exist_ok=True)
    
    def _get_provisioner(self, root_dir: str, scheme, docker_image=None):
        """Get the NVFlare provisioner with all necessary builders"""
        overseer_agent = {
            "path": "nvflare.ha.dummy_overseer_agent.DummyOverseerAgent",
            "overseer_exists": False,
            "args": {"sp_end_point": "server:8002:8003"},  # Default, will be overridden by project props
        }
        
        builders = [
            WorkspaceBuilder(),
            CustomStaticFileBuilder( # Re-enabled with cleaned approach
                config_folder="config",
                scheme=scheme,
                docker_image=docker_image,
                overseer_agent=overseer_agent,
            ),
            AWSBuilder(),
            AzureBuilder(),
            CertBuilder(),
            SignatureBuilder(),
        ]

        # TBD: need to add Packager object to the provisioner!
        packager = None
        return Provisioner(root_dir, builders, packager)
    
    def provision_project(self, project_id, force_reprovision=False):
        """Provision a project using the NVFlare provisioner"""
        print(f"🔍 Starting provision_project with project_id: {project_id}, force_reprovision: {force_reprovision}")
        print(f"🔍 NVFLARE_AVAILABLE: {NVFLARE_AVAILABLE}")
        
        if not NVFLARE_AVAILABLE:
            print("NVFlare not available, falling back to CLI approach")
            return self._provision_via_cli(project_id, force_reprovision)
        
        print("🔍 NVFlare is available, proceeding with API approach")
        print("🔍 Creating custom project.yml for full configuration control")
        
        try:
            # Get project data
            project = Project.query.get(project_id)
            if not project:
                raise ValueError(f"Project {project_id} not found")
            
            servers = Server.query.filter_by(project_id=project_id).all()
            clients = Client.query.filter_by(project_id=project_id).all()
            admins = Admin.query.filter_by(project_id=project_id).all()
            
            print(f"Provisioning project: {project.name}")
            print(f"Servers: {len(servers)}, Clients: {len(clients)}, Admins: {len(admins)}")
            
            # Validate that we have at least one server and one client
            if not servers:
                raise ValueError("No servers configured for this project. Please add at least one server before provisioning.")
            
            if not clients:
                raise ValueError("No clients configured for this project. Please add at least one client before provisioning.")
            
            # Validate that all names are properly set
            for server in servers:
                if not server.name or server.name.strip() == '':
                    raise ValueError(f"Server has empty name. Please set a valid server name.")
                if not server.org or server.org.strip() == '':
                    raise ValueError(f"Server '{server.name}' has empty organization. Please set a valid organization.")
            
            for client in clients:
                if not client.name or client.name.strip() == '':
                    raise ValueError(f"Client has empty name. Please set a valid client name.")
                if not client.org or client.org.strip() == '':
                    raise ValueError(f"Client '{client.name}' has empty organization. Please set a valid organization.")
            
            # Check if already provisioned
            if not force_reprovision:
                existing_workspace = self._get_existing_workspace(project_id)
                if existing_workspace:
                    print(f"Project {project_id} already provisioned, using existing workspace: {existing_workspace}")
                    return existing_workspace
            
                                        # Create temporary directory for provisioning
            print("🔍 Creating temporary directory...")
            with tempfile.TemporaryDirectory() as tmp_dir:
                print(f"✅ Using temporary directory: {tmp_dir}")
                
                # Get provisioner
                print("🔍 Getting project scheme and docker image...")
                scheme = 'agrpc'  # Force agrpc scheme
                docker_image = getattr(project, 'app_location', 'nvflare/nvflare')
                if docker_image and ' ' in docker_image:
                    docker_image = docker_image.split(" ")[-1]
                
                print(f"✅ Scheme: {scheme}, Docker image: {docker_image}")
                
                # Create custom project.yml with correct configuration from database
                print("🔍 Creating custom project.yml...")
                project_yml_path = os.path.join(tmp_dir, 'project.yml')
                self._create_custom_project_yml(project_yml_path, project, servers, clients, admins)
                print(f"✅ Custom project.yml created: {project_yml_path}")
                
                # Use the API approach with the provisioner
                print(f"🔍 Getting provisioner with scheme: {scheme}, docker_image: {docker_image}")
                provisioner = self._get_provisioner(tmp_dir, scheme, docker_image)
                print(f"✅ Provisioner created: {provisioner}")
                
                # Use the custom project.yml file we created
                print("🔍 Using custom project.yml for provisioning...")
                print(f"🔍 Project.yml path: {project_yml_path}")
                
                # Verify the project.yml content
                with open(project_yml_path, 'r') as f:
                    yaml_content = f.read()
                    print(f"📋 Project.yml content:")
                    print(yaml_content)
                
                # Create a minimal ProvProject - the StaticFileBuilder will read from project.yml
                project_name = getattr(project, 'short_name', project.name)
                if not project_name or project_name.strip() == '':
                    project_name = f"project_{project_id}"
                
                print(f"Creating minimal ProvProject with name: {project_name}")
                
                # Set critical properties to override template defaults
                critical_props = {
                    PropKey.SCHEME: 'agrpc',  # Force agrpc scheme
                }
                
                # Add overseer agent configuration to project properties
                if servers:
                    primary_server = servers[0]
                    overseer_endpoint = f"{primary_server.name}:{primary_server.fed_learn_port}:{primary_server.admin_port}"
                    critical_props['overseer_agent'] = {
                        'path': 'nvflare.ha.dummy_overseer_agent.DummyOverseerAgent',
                        'overseer_exists': False,
                        'args': {
                            'sp_end_point': overseer_endpoint
                        }
                    }
                    print(f"🔍 Set project overseer sp_end_point: {overseer_endpoint}")
                
                prov_project = ProvProject(
                    project_name,
                    getattr(project, 'description', '') or f'Project {project_name}',
                    props=critical_props,  # Critical props to override templates
                    root_private_key=None,  # We'll generate this
                    serialized_root_cert=None,  # We'll generate this
                )
                
                
                # Add minimal server/client/admin structure to ProvProject (required by provisioner)
                # The actual configuration will come from the custom project.yml
                if servers:
                    primary_server = servers[0]
                    # print(f"🔍 primary_server: {primary_server.__dict__.__str__()}")

                    server_props = {
                        PropKey.FED_LEARN_PORT: getattr(primary_server, 'fed_learn_port', 8002),
                        PropKey.ADMIN_PORT: getattr(primary_server, 'admin_port', 8003),
                        PropKey.DEFAULT_HOST: getattr(primary_server, 'name', 'FLServer.com'),          
                        # Force the scheme to be agrpc
                        PropKey.SCHEME: 'agrpc',
                        # Configure server to listen on fed_learn_port
                        PropKey.LISTENING_HOST: {
                            PropKey.SCHEME: 'agrpc',
                            PropKey.DEFAULT_HOST: primary_server.name,
                            PropKey.PORT: primary_server.fed_learn_port  # Port 8002
                        },
                        # Add admin_host and admin_port for fed_server.json
                        'admin_host': primary_server.name,
                        'admin_port': primary_server.admin_port,
                        # Add service target configuration
                        'service_target': f"{primary_server.name}:{primary_server.fed_learn_port}",
                        # Add server_identity to match certificate CN
                        'server_identity': primary_server.name,
                        # Add overseer agent configuration
                        'overseer_agent': {
                            'path': 'nvflare.ha.dummy_overseer_agent.DummyOverseerAgent',
                            'args': {
                                'sp_end_point': f"{primary_server.name}:{primary_server.fed_learn_port}:{primary_server.admin_port}"
                            }
                        }
                    }
                    
                    # Add any additional server properties from database
                    if hasattr(primary_server, 'props') and primary_server.props:
                        try:
                            server_props.update(json.loads(primary_server.props))
                            print(f"🔍 additotional Updated server props: {server_props}")
                        except:
                            pass
                    
                    prov_project.set_server(
                        name=primary_server.name,
                        org=primary_server.org or 'nvidia',
                        props=server_props
                    )
                    print(f"🔍 Added server to ProvProject: {primary_server.name}")
                    print(f"🔍 Server props: {server_props}")
                
                if clients:
                    primary_client = clients[0]
                    client_props = {}
                    
                    # Add capacity if available
                    if hasattr(primary_client, 'capacity') and primary_client.capacity:
                        try:
                            client_props[PropKey.CAPACITY] = json.loads(primary_client.capacity)
                        except:
                            pass
                    
                    # Add any additional client properties from database
                    if hasattr(primary_client, 'props') and primary_client.props:
                        try:
                            client_props.update(json.loads(primary_client.props))
                        except:
                            pass
                    
                    prov_project.add_client(
                        name=primary_client.name,
                        org=primary_client.org or 'nvidia',
                        props=client_props
                    )
                    print(f"🔍 Added client to ProvProject: {primary_client.name}")
                    print(f"🔍 Client props: {client_props}")
                
                if admins:
                    primary_admin = admins[0]
                    admin_props = {
                        PropKey.ROLE: getattr(primary_admin, 'role', 'project_admin'),
                        # Admin connects to server's admin_port (8003) for all operations
                        PropKey.CONNECT_TO: {
                            PropKey.NAME: primary_server.name,
                            PropKey.HOST: primary_server.name,
                            PropKey.PORT: primary_server.admin_port  # Port 8003
                        },
                        # Add admin configuration for fed_admin.json
                        'host': primary_server.name,
                        'port': primary_server.admin_port,  # Connect to admin port
                        'scheme': 'agrpc',
                        'with_file_transfer': True,
                        'upload_dir': 'transfer',
                        'download_dir': 'transfer',
                        'with_login': True,
                        'with_ssl': True,
                        'cred_type': 'cert',
                        'prompt': '> ',
                        # Add server_identity to match certificate CN
                        'server_identity': primary_server.name,
                        # Add overseer agent configuration
                        'overseer_agent': {
                            'path': 'nvflare.ha.dummy_overseer_agent.DummyOverseerAgent',
                            'args': {
                                'sp_end_point': f"{primary_server.name}:{primary_server.fed_learn_port}:{primary_server.admin_port}"
                            }
                        }
                    }
                    
                    # Add any additional admin properties from database
                    if hasattr(primary_admin, 'props') and primary_admin.props:
                        try:
                            admin_props.update(json.loads(primary_admin.props))
                        except:
                            pass
                    
                    prov_project.add_admin(
                        name=primary_admin.email,
                        org=primary_admin.org or 'nvidia',
                        props=admin_props
                    )
                
                print(f"ProvProject created successfully: {prov_project._all_names}, {prov_project._participants_by_types}, {prov_project.props}, {prov_project.overseer}, {prov_project.server},  ")

                print(f"🔍 ProvProject: {prov_project.props}")
                # Provision the project using the custom project.yml
                print("Calling provisioner.provision() with custom project.yml...")
                result_ctx = provisioner.provision(prov_project)
                # print(f"Provisioning completed. Result context: {result_ctx}")
                
                # Extract the result directory from the context
                if hasattr(result_ctx, 'get_result_location'):
                    result_dir = result_ctx.get_result_location()
                elif hasattr(result_ctx, 'result_location'):
                    result_dir = result_ctx.result_location
                else:
                    # Try to find the result directory in the temporary directory
                    result_dir = os.path.join(tmp_dir, "project_2", "prod_00")
                    if not os.path.exists(result_dir):
                        # Look for any directory that might contain the results
                        for item in os.listdir(tmp_dir):
                            item_path = os.path.join(tmp_dir, item)
                            if os.path.isdir(item_path):
                                prod_dir = os.path.join(item_path, "prod_00")
                                if os.path.exists(prod_dir):
                                    result_dir = prod_dir
                                    break
                
                print(f"Result directory: {result_dir}")
                
                if not result_dir or not os.path.exists(result_dir):
                    raise ValueError(f"Could not find result directory from provisioning")
                
                # Copy to final workspace
                final_workspace = os.path.join(self.workspace_dir, f"project_{project_id}")
                if os.path.exists(final_workspace):
                    shutil.rmtree(final_workspace)
                
                shutil.copytree(result_dir, final_workspace)
                print(f"Copied to final workspace: {final_workspace}")
                
                return final_workspace
                
        except Exception as e:
            print(f"Error provisioning project: {e}")
            import traceback
            traceback.print_exc()
            return None
    
    def _provision_via_cli(self, project_id, force_reprovision=False):
        """Fallback to CLI provisioning if NVFlare is not available"""
        print("Using CLI fallback provisioning...")
        # This would call the existing CLI-based provisioning
        # For now, just return None to indicate fallback needed
        return None
    
    def _get_existing_workspace(self, project_id):
        """Get existing workspace if project is already provisioned"""
        workspace = os.path.join(self.workspace_dir, f"project_{project_id}")
        if not os.path.exists(workspace):
            return None
        
        # Look for the prod_00 directory
        for item in os.listdir(workspace):
            project_dir = os.path.join(workspace, item)
            if os.path.isdir(project_dir):
                prod_dir = os.path.join(project_dir, 'prod_00')
                if os.path.exists(prod_dir):
                    return prod_dir
        
        return None
    
    def generate_startup_kit(self, project_id, item_type, item_id=None):
        """Generate startup kit for a specific item or the entire project"""
        workspace = self._get_existing_workspace(project_id)
        if not workspace:
            raise ValueError(f"Project {project_id} not provisioned")
        
        if item_type == 'all':
            return self._generate_all_startup_kits(workspace)
        else:
            return self._generate_item_startup_kit(workspace, item_type, item_id)
    
    def _generate_item_startup_kit(self, workspace, item_type, item_id):
        """Generate startup kit for a specific item"""
        # Find the appropriate directory based on item type
        target_dir = None
        
        for item in os.listdir(workspace):
            item_path = os.path.join(workspace, item)
            if os.path.isdir(item_path):
                if item_type == 'server' and (item.endswith('.com') or item.endswith('.org')):
                    target_dir = item_path
                    break
                elif item_type == 'client' and item.startswith('site-'):
                    target_dir = item_path
                    break
                elif item_type == 'admin' and '@' in item:
                    target_dir = item_path
                    break
        
        if not target_dir:
            raise ValueError(f"Could not find {item_type} directory in workspace")
        
        # Create zip file
        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            for root, dirs, files in os.walk(target_dir):
                for file in files:
                    file_path = os.path.join(root, file)
                    arc_name = os.path.relpath(file_path, target_dir)
                    zip_file.write(file_path, arc_name)
        
        zip_buffer.seek(0)
        return zip_buffer, f"{os.path.basename(target_dir)}.zip"
    
    def _generate_all_startup_kits(self, workspace):
        """Generate startup kits for all items"""
        all_kits = {}
        
        for item in os.listdir(workspace):
            item_path = os.path.join(workspace, item)
            if os.path.isdir(item_path):
                if item.endswith('.com') or item.endswith('.org'):
                    # Server
                    kit_buffer, kit_name = self._generate_item_startup_kit(workspace, 'server', None)
                    all_kits['server'] = (kit_buffer, kit_name)
                elif item.startswith('site-'):
                    # Client
                    kit_buffer, kit_name = self._generate_item_startup_kit(workspace, 'client', None)
                    all_kits['client'] = (kit_buffer, kit_name)
                elif '@' in item:
                    # Admin
                    kit_buffer, kit_name = self._generate_item_startup_kit(workspace, 'admin', None)
                    all_kits['admin'] = (kit_buffer, kit_name)
        
        return all_kits
    

    def _create_custom_project_yml(self, project_yml_path, project, servers, clients, admins):
        """Create a custom project.yml with the correct configurations"""
        import yaml
        
        # Create the project configuration
        project_config = {
            'api_version': 3,
            'name': getattr(project, 'short_name', project.name) or f"project_{project.id}",
            'description': getattr(project, 'description', '') or f'Project {project.name}',
            'scheme': 'agrpc',  # Force agrpc scheme
            'overseer_agent': {
                'path': 'nvflare.ha.dummy_overseer_agent.DummyOverseerAgent',
                'overseer_exists': False,
                'args': {}
            }
        }
        
        # Set overseer endpoint if we have servers
        if servers:
            primary_server = servers[0]
            project_config['overseer_agent']['args']['sp_end_point'] = f"{primary_server.name}:{primary_server.fed_learn_port}:{primary_server.admin_port}"
        else:
            project_config['overseer_agent']['args']['sp_end_point'] = "server:8002:8003"
        
        # Add servers
        if servers:
            project_config['servers'] = []
            for server in servers:
                server_config = {
                    'name': server.name,
                    'org': server.org or 'nvidia',
                    'props': {
                        'fed_learn_port': server.fed_learn_port,
                        'admin_port': server.admin_port,
                        'scheme': 'agrpc',  # Force agrpc scheme
                        'service_target': f"{server.name}:{server.fed_learn_port}:{server.admin_port}",  # Custom property for service target
                        'admin_host': server.name,
                        'admin_port': server.admin_port,
                        'server_identity': server.name,  # Add server_identity to match certificate CN
                        'overseer_agent': {
                            'path': 'nvflare.ha.dummy_overseer_agent.DummyOverseerAgent',
                            'args': {
                                'sp_end_point': f"{server.name}:{server.fed_learn_port}:{server.admin_port}"
                            }
                        }
                    }
                }
                project_config['servers'].append(server_config)
        
        # Add clients
        if clients:
            project_config['clients'] = []
            for client in clients:
                client_config = {
                    'name': client.name,
                    'org': client.org or 'nvidia',
                    'props': {}
                }
                if hasattr(client, 'capacity') and client.capacity:
                    try:
                        client_config['props']['capacity'] = json.loads(client.capacity)
                    except:
                        pass
                project_config['clients'].append(client_config)
        
        # Add admins
        if admins:
            project_config['admins'] = []
            for admin in admins:
                admin_config = {
                    'name': admin.email,
                    'org': admin.org or 'nvidia',
                    'props': {
                        'role': getattr(admin, 'role', 'project_admin'),
                        'host': primary_server.name,
                        'port': primary_server.admin_port,
                        'scheme': 'agrpc',
                        'with_file_transfer': True,
                        'upload_dir': 'transfer',
                        'download_dir': 'transfer',
                        'with_login': True,
                        'with_ssl': True,
                        'cred_type': 'cert',
                        'prompt': '> ',
                        'server_identity': primary_server.name,  # Add server_identity to match certificate CN
                        'overseer_agent': {
                            'path': 'nvflare.ha.dummy_overseer_agent.DummyOverseerAgent',
                            'args': {
                                'sp_end_point': f"{primary_server.name}:{primary_server.fed_learn_port}:{primary_server.admin_port}"
                            }
                        }
                    }
                }
                project_config['admins'].append(admin_config)
        
        # Write the configuration to file
        with open(project_yml_path, 'w') as f:
            yaml.dump(project_config, f, default_flow_style=False, sort_keys=False)
        
        print(f"Created custom project.yml: {project_yml_path}")
        print(f"Project config: {yaml.dump(project_config, default_flow_style=False, sort_keys=False)}")
    
    def _provision_via_cli_with_custom_yml(self, project_id, project_yml_path, force_reprovision=False):
        """Use the CLI approach with our custom project.yml"""
        try:
            # Check if already provisioned
            if not force_reprovision:
                existing_workspace = self._get_existing_workspace(project_id)
                if existing_workspace:
                    print(f"Project {project_id} already provisioned, using existing workspace: {existing_workspace}")
                    return existing_workspace
            
            # Create the project.yml file dynamically
            if not project_yml_path:
                project_yml_path = self._create_dynamic_project_yml(project_id)
            
            # Create temporary workspace directory
            with tempfile.TemporaryDirectory() as tmp_workspace:
                print(f"Using temporary workspace: {tmp_workspace}")
                
                # Run nvflare provision command
                cmd = [
                    'nvflare', 'provision',
                    '-p', project_yml_path,
                    '-w', tmp_workspace
                ]
                
                print(f"Running command: {' '.join(cmd)}")
                result = subprocess.run(cmd, capture_output=True, text=True, cwd=os.path.dirname(project_yml_path))
                
                if result.returncode != 0:
                    print(f"❌ CLI provisioning failed:")
                    print(f"STDOUT: {result.stdout}")
                    print(f"STDERR: {result.stderr}")
                    raise Exception(f"CLI provisioning failed with return code {result.returncode}")
                
                print(f"✅ CLI provisioning successful:")
                print(f"STDOUT: {result.stdout}")
                
                # Copy to final workspace
                final_workspace = os.path.join(self.workspace_dir, f"project_{project_id}")
                if os.path.exists(final_workspace):
                    shutil.rmtree(final_workspace)
                
                shutil.copytree(tmp_workspace, final_workspace)
                print(f"Copied to final workspace: {final_workspace}")
                
                return final_workspace
                
        except Exception as e:
            print(f"Error in CLI provisioning: {e}")
            import traceback
            traceback.print_exc()
            return None
    
    def _create_dynamic_project_yml(self, project_id):
        """Create a dynamic project.yml file with the correct configuration"""
        import yaml
        
        # Get project data
        project = Project.query.get(project_id)
        servers = Server.query.filter_by(project_id=project_id).all()
        clients = Client.query.filter_by(project_id=project_id).all()
        admins = Admin.query.filter_by(project_id=project_id).all()
        
        # Create the project configuration
        project_config = {
            'api_version': 3,
            'name': getattr(project, 'short_name', project.name) or f"project_{project.id}",
            'description': getattr(project, 'description', '') or f'Project {project.name}',
            'scheme': 'agrpc',  # Force agrpc scheme
            'overseer_agent': {
                'path': 'nvflare.ha.dummy_overseer_agent.DummyOverseerAgent',
                'overseer_exists': False,
                'args': {}
            }
        }
        
        # Set overseer endpoint if we have servers
        if servers:
            primary_server = servers[0]
            project_config['overseer_agent']['args']['sp_end_point'] = f"{primary_server.name}:{primary_server.fed_learn_port}:{primary_server.admin_port}"
        else:
            project_config['overseer_agent']['args']['sp_end_point'] = "server:8002:8003"
        
        # Add servers
        if servers:
            project_config['servers'] = []
            for server in servers:
                server_config = {
                    'name': server.name,
                    'org': server.org or 'nvidia',
                    'props': {
                        'fed_learn_port': server.fed_learn_port,
                        'admin_port': server.admin_port,
                        'scheme': 'agrpc'  # Force agrpc scheme
                    }
                }
                project_config['servers'].append(server_config)
        
        # Add clients
        if clients:
            project_config['clients'] = []
            for client in clients:
                client_config = {
                    'name': client.name,
                    'org': client.org or 'nvidia',
                    'props': {}
                }
                if hasattr(client, 'capacity') and client.capacity:
                    try:
                        client_config['props']['capacity'] = json.loads(client.capacity)
                    except:
                        pass
                project_config['clients'].append(client_config)
        
        # Add admins
        if admins:
            project_config['admins'] = []
            for admin in admins:
                admin_config = {
                    'name': admin.email,
                    'org': admin.org or 'nvidia',
                    'props': {
                        'role': getattr(admin, 'role', 'project_admin')
                    }
                }
                project_config['admins'].append(admin_config)
        
        # Create temporary file
        import tempfile
        fd, project_yml_path = tempfile.mkstemp(suffix='.yml', prefix='project_')
        os.close(fd)
        
        # Write the configuration to file
        with open(project_yml_path, 'w') as f:
            yaml.dump(project_config, f, default_flow_style=False, sort_keys=False)
        
        print(f"Created dynamic project.yml: {project_yml_path}")
        print(f"Project config: {yaml.dump(project_config, default_flow_style=False, sort_keys=False)}")
        
        return project_yml_path
